// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modify.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCSIDriverModificationCapabilityRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCSIDriverModificationCapabilityRequest) Reset() {
	*m = GetCSIDriverModificationCapabilityRequest{}
}
func (m *GetCSIDriverModificationCapabilityRequest) String() string { return proto.CompactTextString(m) }
func (*GetCSIDriverModificationCapabilityRequest) ProtoMessage()    {}
func (*GetCSIDriverModificationCapabilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c5ffd21f9bd0c1, []int{0}
}

func (m *GetCSIDriverModificationCapabilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCSIDriverModificationCapabilityRequest.Unmarshal(m, b)
}
func (m *GetCSIDriverModificationCapabilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCSIDriverModificationCapabilityRequest.Marshal(b, m, deterministic)
}
func (m *GetCSIDriverModificationCapabilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCSIDriverModificationCapabilityRequest.Merge(m, src)
}
func (m *GetCSIDriverModificationCapabilityRequest) XXX_Size() int {
	return xxx_messageInfo_GetCSIDriverModificationCapabilityRequest.Size(m)
}
func (m *GetCSIDriverModificationCapabilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCSIDriverModificationCapabilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCSIDriverModificationCapabilityRequest proto.InternalMessageInfo

type GetCSIDriverModificationCapabilityResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCSIDriverModificationCapabilityResponse) Reset() {
	*m = GetCSIDriverModificationCapabilityResponse{}
}
func (m *GetCSIDriverModificationCapabilityResponse) String() string {
	return proto.CompactTextString(m)
}
func (*GetCSIDriverModificationCapabilityResponse) ProtoMessage() {}
func (*GetCSIDriverModificationCapabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c5ffd21f9bd0c1, []int{1}
}

func (m *GetCSIDriverModificationCapabilityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCSIDriverModificationCapabilityResponse.Unmarshal(m, b)
}
func (m *GetCSIDriverModificationCapabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCSIDriverModificationCapabilityResponse.Marshal(b, m, deterministic)
}
func (m *GetCSIDriverModificationCapabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCSIDriverModificationCapabilityResponse.Merge(m, src)
}
func (m *GetCSIDriverModificationCapabilityResponse) XXX_Size() int {
	return xxx_messageInfo_GetCSIDriverModificationCapabilityResponse.Size(m)
}
func (m *GetCSIDriverModificationCapabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCSIDriverModificationCapabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCSIDriverModificationCapabilityResponse proto.InternalMessageInfo

type ModifyVolumePropertiesRequest struct {
	// Name of the volume.
	// This field is REQUIRED.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// New volume attributes.
	// This field is REQUIRED.
	Parameters map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Contains additional information that
	// may be required by driver.
	Context              map[string]string `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ModifyVolumePropertiesRequest) Reset()         { *m = ModifyVolumePropertiesRequest{} }
func (m *ModifyVolumePropertiesRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyVolumePropertiesRequest) ProtoMessage()    {}
func (*ModifyVolumePropertiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c5ffd21f9bd0c1, []int{2}
}

func (m *ModifyVolumePropertiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyVolumePropertiesRequest.Unmarshal(m, b)
}
func (m *ModifyVolumePropertiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyVolumePropertiesRequest.Marshal(b, m, deterministic)
}
func (m *ModifyVolumePropertiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyVolumePropertiesRequest.Merge(m, src)
}
func (m *ModifyVolumePropertiesRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyVolumePropertiesRequest.Size(m)
}
func (m *ModifyVolumePropertiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyVolumePropertiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyVolumePropertiesRequest proto.InternalMessageInfo

func (m *ModifyVolumePropertiesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifyVolumePropertiesRequest) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *ModifyVolumePropertiesRequest) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

type ModifyVolumePropertiesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyVolumePropertiesResponse) Reset()         { *m = ModifyVolumePropertiesResponse{} }
func (m *ModifyVolumePropertiesResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyVolumePropertiesResponse) ProtoMessage()    {}
func (*ModifyVolumePropertiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c5ffd21f9bd0c1, []int{3}
}

func (m *ModifyVolumePropertiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyVolumePropertiesResponse.Unmarshal(m, b)
}
func (m *ModifyVolumePropertiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyVolumePropertiesResponse.Marshal(b, m, deterministic)
}
func (m *ModifyVolumePropertiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyVolumePropertiesResponse.Merge(m, src)
}
func (m *ModifyVolumePropertiesResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyVolumePropertiesResponse.Size(m)
}
func (m *ModifyVolumePropertiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyVolumePropertiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyVolumePropertiesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetCSIDriverModificationCapabilityRequest)(nil), "modify.v1.GetCSIDriverModificationCapabilityRequest")
	proto.RegisterType((*GetCSIDriverModificationCapabilityResponse)(nil), "modify.v1.GetCSIDriverModificationCapabilityResponse")
	proto.RegisterType((*ModifyVolumePropertiesRequest)(nil), "modify.v1.ModifyVolumePropertiesRequest")
	proto.RegisterMapType((map[string]string)(nil), "modify.v1.ModifyVolumePropertiesRequest.ContextEntry")
	proto.RegisterMapType((map[string]string)(nil), "modify.v1.ModifyVolumePropertiesRequest.ParametersEntry")
	proto.RegisterType((*ModifyVolumePropertiesResponse)(nil), "modify.v1.ModifyVolumePropertiesResponse")
}

func init() {
	proto.RegisterFile("modify.proto", fileDescriptor_d6c5ffd21f9bd0c1)
}

var fileDescriptor_d6c5ffd21f9bd0c1 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdd, 0x4a, 0xe3, 0x40,
	0x14, 0xc7, 0x37, 0xe9, 0x6e, 0x97, 0x9e, 0x2d, 0xec, 0x32, 0x2c, 0x4b, 0x08, 0xac, 0x84, 0x5c,
	0xb5, 0x6a, 0x13, 0xac, 0x16, 0x4a, 0xc1, 0x1b, 0xab, 0x88, 0x17, 0x62, 0xa9, 0x20, 0xe2, 0x5d,
	0x92, 0x9e, 0xc6, 0xa1, 0x49, 0x66, 0x9c, 0x4c, 0x82, 0x79, 0x0a, 0x2f, 0x7c, 0x3a, 0xdf, 0x46,
	0x3a, 0x49, 0x4b, 0x11, 0x3f, 0xd2, 0xbb, 0x73, 0x92, 0xff, 0xff, 0x77, 0x72, 0x3e, 0x02, 0xed,
	0x98, 0xcd, 0xe8, 0xbc, 0x70, 0xb8, 0x60, 0x92, 0x91, 0x56, 0x95, 0xe5, 0x07, 0xa6, 0x15, 0x32,
	0x16, 0x46, 0xe8, 0xaa, 0x17, 0x7e, 0x36, 0x77, 0x67, 0x98, 0x06, 0x82, 0x72, 0xc9, 0x44, 0x29,
	0xb6, 0xf7, 0xa0, 0x7b, 0x8e, 0x72, 0x7c, 0x7d, 0x71, 0x2a, 0x68, 0x8e, 0xe2, 0x72, 0x69, 0xa5,
	0x81, 0x27, 0x29, 0x4b, 0xc6, 0x1e, 0xf7, 0x7c, 0x1a, 0x51, 0x59, 0x4c, 0xf1, 0x21, 0xc3, 0x54,
	0xda, 0xfb, 0xb0, 0x5b, 0x47, 0x9c, 0x72, 0x96, 0xa4, 0x68, 0xbf, 0xe8, 0xf0, 0x5f, 0x49, 0x8a,
	0x1b, 0x16, 0x65, 0x31, 0x4e, 0x04, 0xe3, 0x28, 0x24, 0xc5, 0xb4, 0xe2, 0x11, 0x02, 0xdf, 0x13,
	0x2f, 0x46, 0x43, 0xb3, 0xb4, 0x4e, 0x6b, 0xaa, 0x62, 0x72, 0x0b, 0xc0, 0x3d, 0xe1, 0xc5, 0x28,
	0x51, 0xa4, 0x86, 0x6e, 0x35, 0x3a, 0xbf, 0xfa, 0x43, 0x67, 0xdd, 0x92, 0xf3, 0x29, 0xd1, 0x99,
	0xac, 0xad, 0x67, 0x89, 0x14, 0xc5, 0x74, 0x83, 0x45, 0xae, 0xe0, 0x67, 0xc0, 0x12, 0x89, 0x8f,
	0xd2, 0x68, 0x28, 0xec, 0xa0, 0x36, 0x76, 0x5c, 0xfa, 0x4a, 0xe6, 0x8a, 0x62, 0x1e, 0xc3, 0xef,
	0x37, 0xf5, 0xc8, 0x1f, 0x68, 0x2c, 0xb0, 0xa8, 0x1a, 0x5a, 0x86, 0xe4, 0x2f, 0xfc, 0xc8, 0xbd,
	0x28, 0x43, 0x43, 0x57, 0xcf, 0xca, 0x64, 0xa4, 0x0f, 0x35, 0x73, 0x04, 0xed, 0x4d, 0xee, 0x36,
	0x5e, 0xdb, 0x82, 0x9d, 0x8f, 0xbe, 0xb8, 0x9c, 0x7e, 0xff, 0x49, 0x87, 0x66, 0x29, 0x21, 0xcf,
	0x1a, 0xd8, 0x5f, 0xef, 0x8d, 0x1c, 0x6d, 0x8c, 0xa3, 0xf6, 0x4d, 0x98, 0x83, 0x2d, 0x5d, 0xd5,
	0x71, 0x7c, 0x23, 0x0c, 0xfe, 0xbd, 0xdf, 0x02, 0xe9, 0xd4, 0xdd, 0x8b, 0xd9, 0xad, 0xa1, 0x5c,
	0x15, 0x3c, 0x19, 0xdd, 0x0d, 0x43, 0x2a, 0xef, 0x33, 0xdf, 0x09, 0x58, 0xec, 0xe6, 0x49, 0x18,
	0x44, 0x2c, 0x9b, 0xad, 0x83, 0x5e, 0x90, 0xd2, 0x5e, 0xae, 0xec, 0x3d, 0x45, 0xa5, 0x28, 0x5c,
	0xbe, 0x08, 0x5d, 0xc1, 0x03, 0xbf, 0xa9, 0xfe, 0x96, 0xc3, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x1f, 0xd2, 0xfb, 0xd3, 0x6a, 0x03, 0x00, 0x00,
}
