name: Release vngcloud-csi-volume-modifier project

on:
  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Send alert that a new release has been created
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🚀 *[RELEASE] NEW RELEASE*
            *Repository*: `${{ github.repository }}`
            *Author*: `${{ github.actor }}`
            *Action*: Building `vngcloud-csi-volume-modifier:${{ github.ref_name }}` application
            *Commit message*:
            ```text
            ${{ github.event.commits[0].message }}
            ```
            *See changes*: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            *See workflow*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        continue-on-error: true
        with:
          go-version: 1.22
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        continue-on-error: true
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
      - name: Send alert that the image has been built failed
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ⛔ *[RELEASE] ERROR*
            *Repository*: `${{ github.repository }}`
            *Author*: `${{ github.actor }}`
            *Action*: Failed to release `vngcloud-csi-volume-modifier:${{ github.ref_name }}` application
            *Commit message*:
            ```text
            ${{ github.event.commits[0].message }}
            ```
            *See changes*: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            *See workflow*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Send alert that the image has been built success
        uses: appleboy/telegram-action@master
        if: ${{ success() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            📦 *[RELEASE] SUCCESS*
            *Repository*: `${{ github.repository }}`
            *Author*: `${{ github.actor }}`
            *Action*: The `vngcloud-csi-volume-modifier:${{ github.ref_name }}` application is built successfully
            *Commit message*:
            ```text
            ${{ github.event.commits[0].message }}
            ```
            *See changes*: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            *See workflow*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}